### PR TITLE
add sort packages

### PR DESCRIPTION
**Pull request by connorhu**
minor add

### CODE REVIEW

**Comment by thePanz** [comment]
how can we ensure that the ordering is kept?

the reqs are not sorted as an example, we might need to use compose-normalizer and add a CI action?

**Comment by connorhu** [comment]
composer does the sorting when you add new `req` or `req-dev` package:
https://getcomposer.org/doc/06-config.md#sort-packages

**Comment by thePanz** [comment]
> composer does the sorting when you add new `req` or `req-dev` package: https://getcomposer.org/doc/06-config.md#sort-packages

Yeah, i know that.
What I was addressing is the fact that our composer.json is not yet sorted, and there is nothing in place to verify that the sorting is respected on merging new PRs :)

**Comment by connorhu** [comment]
Oooo i see. Sorry I didn't notice that the ext's are not sorted.

**Review by alquerci — APPROVED** [review]

**Review by thirsch — APPROVED** [review]

**Review by thePanz — APPROVED** [review]

**Pull request merged**
